version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "8084:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

  golang-server-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang-server-1
    environment:
      - SERVER_NAME=Server1
    ports:
      - "8081:8080"

  golang-server-2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang-server-2
    environment:
      - SERVER_NAME=Server2
    ports:
      - "8082:8080"

  golang-server-3:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang-server-3
    environment:
      - SERVER_NAME=Server3
    ports:
      - "8083:8080"
